# Mathematic Operation Using NumPy

In [1]:
import numpy as np

In [4]:
#creatin 2D array
arr1= np.arange(1,10).reshape(3,3)
arr2= np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr1+arr2 # OR np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
# subtract 2 arrays
np.subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
# divide 2 arrays
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [9]:
# matrix product 
arr1 @ arr2 # arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [21]:
# find max value in array
arr1.max()

9

In [11]:
# index of max value 
arr1.argmax()

8

In [17]:
# find max value in row(axis=1) and col(axis=0)
a=arr1.max(axis=0)
b=arr1.max(axis=1)
print("Max in column: ",a)
print("Max in row: ",b)

Max in column:  [7 8 9]
Max in row:  [3 6 9]


In [18]:
#sum of all elements of array
np.sum(arr1)

45

In [20]:
#sum of all elements in a row and column
x= np.sum(arr1, axis=0)
y= np.sum(arr1, axis=1)
print("Sum of columns:",x)
print("Sum of rows:",y)

Sum of columns: [12 15 18]
Sum of rows: [ 6 15 24]


In [23]:
arr1.sum(axis=0)

array([12, 15, 18])

In [24]:
arr1.mean()

5.0

In [26]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [30]:
#standard deviation
np.std(arr1)

2.581988897471611

In [29]:
#exponent
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [33]:
#log
np.log(arr1)
#for log base 10 np.log10(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])