# NumPy Function:

In [1]:
import numpy as np

# arange()

In [2]:
#creates array in numpy
#np.arrange(start, end, steps)

arr1= np.arange(1,13)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
evenArr= np.arange(0,13,2)
print(evenArr)

[ 0  2  4  6  8 10 12]


# linspace()

In [8]:
#if we want n no. of random values in a range (-,-,n)
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [10]:
#converts 1d array to 2d array (rows,clos)
arr2= arr1.reshape(2,6)
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [11]:
#converts 1d array to 3d array (3d,2d,1d)
arr3= arr1.reshape(2,3,2)
print(arr3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel()

In [13]:
#converts multidimensional array to 1D
arr3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [14]:
#converts multidimensional array to 1D

# transpose()

In [16]:
arr2.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [17]:
arr2.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])