# Random Sampling with Numpy


In [1]:
import numpy as np

In [6]:
import random

In [13]:
#gives value between 0-1
np.random.rand(4)

array([0.93591796, 0.80546464, 0.80622792, 0.79546592])

In [11]:
#when we want a single random integer values we use 
# randint (range ,range , (shape))
np.random.randint(1,4)

2

In [9]:
np.random.randint(1,4,(4,4))

array([[1, 3, 3, 1],
       [2, 1, 3, 1],
       [1, 1, 1, 3],
       [3, 2, 1, 3]])

In [14]:
# if we use randn() then we get negative value also 
np.random.randn(3,3)

array([[-1.44725904,  0.75732195,  0.87918721],
       [-2.017132  , -0.41414681,  0.31491074],
       [ 0.8047987 ,  0.12093609,  0.41708465]])

In [25]:
 x= [1,2,3,4]
np.random.choice(x)

3

In [28]:
for i in range(10):
    print(np.random.choice(x))

3
2
4
2
4
4
1
1
1
1


In [29]:
# finding diffrent permutations we can use shuffle
np.random.permutation(x)

array([1, 2, 4, 3])